### ISSUE TITLE
is it possible for two animations from different files to exist?

### ISSUE THREAD

**Issue by IzabourAzevedo** [rive-app/rive-ios#324]
is it possible for two animations from different files to exist? and they work separately but as soon as i say i need one to be enabled only in long press it doesn't work.

RiveRuntime/RiveViewModel.swift:213: Fatal error: 'try!' expression unexpectedly raised an error: RiveRuntime.RiveModel.RiveModelError.invalidAnimation("Name hana not found")

VStack {
            if isLongPressed {
                secondaryRiveViewModel.view()
                    .frame(width: 360, height: 136)
                    .onAppear {
                        secondaryRiveViewModel.play(animationName: "hanasad")
                    }
            } else {
                riveViewModel.view()
                    .frame(width: 360, height: 136)
                    .onAppear {
                        setupRive()
                    }
            }
        }
        .gesture(
            LongPressGesture(minimumDuration: 1.0)
                .onChanged { _ in
                    handleLongPress()
                }
                .onEnded { _ in
                    isLongPressed = false
                }
        )
    }

**Comment by dskuza** [comment]
@IzabourAzevedo It should be possible, so long as you have separate view models, which it looks like you do. Are you still experiencing this issue? It looks like you might be using an animation name that doesn't match that in your exported `.riv` file.

**Comment by dskuza** [comment]
Closing this issue as stale.
